apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  amer-west-project-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: amer-west-project-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZPakNDQkNLZ0F3SUJBZ0lTQkdCNnVNVWpBbDZLRlF0QkJYSk5PR2dyTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlOREEwTWpReE1qVTRNemxhRncweU5EQTNNak14TWpVNE16aGFNQ1V4SXpBaEJnTlZCQU1UCkdtRndhUzUwWVc1NmRTNWpiRzkxWkM1MmJYZGhjbVV1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQTZWbmR3NE9QQW8xQWE1NkNBWHU5UnlmYllnUnNwM1RHdVphNE1hUFNzNXM2VFVERgplcnRoWXJmNXRZREl6WmpaVXhwMFpnRDROLytJTDZ1ZkcvQWpiaTRKNHRaU2d5OUNIODBWSjNqcG1yVnlVZXFUCkxEQzlCbjNQYUt0YTNSYS90d0JVSjNlWXJjaEwvSHJGMW14ZStpVkFWL0lTS2xTMFg1OHNySHVQVlltQStwTlAKalcxQjcyL1NPVUtTVzRwMGc5SzQ1WnQzcWplaDlmZERuTEFZcEliR3hwaTBIcEl1VFNhOHhmd1MrQzRuNTYwOApOOFN5VHdMdy9hMVJTVXFpb3F6Rzd3QS9yeUtMeVI4UVJ3RlloYzlRTlUxVFV3cWtCVHJIQmdoeTR3SEZkMklvCmFwOHlsS1NpMjl3UzhEdHVKVnIxTWpnWnZUM1VoM3YwVEhIb1NRSURBUUFCbzRJQ1ZUQ0NBbEV3RGdZRFZSMFAKQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQgpBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUzJJb2xFM01QWldzQzdySXFYZnZVZG1RMU9YekFmQmdOVkhTTUVHREFXCmdCUVVMck1YdDFoV3k2NVFDVURtSDYrZGl4VEN4akJWQmdnckJnRUZCUWNCQVFSSk1FY3dJUVlJS3dZQkJRVUgKTUFHR0ZXaDBkSEE2THk5eU15NXZMbXhsYm1OeUxtOXlaekFpQmdnckJnRUZCUWN3QW9ZV2FIUjBjRG92TDNJegpMbWt1YkdWdVkzSXViM0puTHpCZEJnTlZIUkVFVmpCVWdocGhjR2t1ZEdGdWVuVXVZMnh2ZFdRdWRtMTNZWEpsCkxtTnZiWUlhZEcxakxuUmhibnAxTG1Oc2IzVmtMblp0ZDJGeVpTNWpiMjJDR25SemJTNTBZVzU2ZFM1amJHOTEKWkM1MmJYZGhjbVV1WTI5dE1CTUdBMVVkSUFRTU1Bb3dDQVlHWjRFTUFRSUJNSUlCQlFZS0t3WUJCQUhXZVFJRQpBZ1NCOWdTQjh3RHhBSFlBUHhkTFQ5Y2lSMWlVSFdVY2hMNE5FdTJRTjM4ZmhXcnJ3YjhvaGV6NFpHNEFBQUdQCkVHYThid0FBQkFNQVJ6QkZBaUFCNThwU3c2N1NTQ2s2YlBvTWN6ai94QVZhYUxJdnBWbkRtTk1WdmNtVUh3SWgKQU56T3JVRXRPYzNkdmYyVTIwRjhEeVAvUWpaWVRDVUQ4Ui9tZk9LUnZXaDJBSGNBU0xEamE5cW1SelFQNVdvQworcDB3Nnh4U0FjdFczU3lCMmJ1L3F6blloSE1BQUFHUEVHYThjUUFBQkFNQVNEQkdBaUVBODhPTm5kYVd3azR1CmtJKzR0UDNrblRSdjVQNlkrcldSYmFDaGVoTTBwaGNDSVFEQXhQZlAvUWVxR2UveXJwejBSVGludk1KOXRKYmcKeVo5aVI2eGdWdGNrWkRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXVvVlJoYUlpN2lzbjN0TWVFSWhNQXJ3OQpNc1dKSHBDWTRVMVlQd29TQ3ZTSjYyUnR6U3JHM1hYOEFRQ3FtTnFWT1dyQk9aYTVERnhrMk43ZDVOV0Z4azFTCmhuWW52cmVOZ21SdjEvdHpaNytlM1lKZ21OZHFEWjVXZnp6MDJxNzQ3d3doUEQ3L1J4aStSNTlXY0F4MzBYM3oKcGQvaVhyUTNJREJuVlZhU0xobnRlWndtbHBJY2VUVVRvTXRsdHdmdDVSc3RDNVVabUlSMVlkUU9FTUpDUWVHVQpBU05zNFYrd3FBUVlIU0hLR1ltcTIzeEdpcGlPbXpCSXFHZlFFejhQMm9aZVhhRlVKU0l6YUlVNHZ3cmNEbEVMCit4VGlYNkFNbXNZM2x5U0c0amNVSjJEYzg2bTNwNTJQSGJXQ0JKSWJSY1QyVG4yQkxaUldsREJUNHVlQzlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
              server: https://api.tanzu.cloud.vmware.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b
            name: sa-tanzu-platform:AMER-West
          contexts:
          - context:
              cluster: sa-tanzu-platform:AMER-West
              user: sa-tanzu-platform-user
            name: sa-tanzu-platform:AMER-West
          current-context: sa-tanzu-platform:AMER-West
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

