apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ucp-token-generator
resources:
- deployment.yml
- rbac.yml

secretGenerator:
- name: token-generator-env
  envs:
  - generator.env